# Generated by Django 6.0 on 2026-01-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_formdefinition_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='key',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
