# Generated by Django 6.0 on 2026-01-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_formfield_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='key',
            field=models.SlugField(max_length=255),
        ),
    ]
