# Generated by Django 6.0 on 2026-01-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_formfield_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='key',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
